### ISSUE TITLE
Task List -- Quiz 1 Analysis

### ISSUE THREAD

**Issue by Page007** [Page007/rutvikpage#1]
Following are the things to do on Monday, Apr 1: 

- [x] Lecture 7 preparation
- [x] Revising definitions from lecture 4-6
- [x] PSET 1 question 1 to be done using contradiction 
- [x] Questions from the list of questions mentioned on lecture 6.

The particulars of each of these tasks needs to be observed from the file: `rutvikpage/Analysis/Q1Prep.md`.

**Comment by rutvikpage** [comment]
Things to be kept in mind: 
Remember, the solution to any question goes through careful logical steps. Think first about the logic, start executing it in math and improvise later. Knowing why $a \implies b$ is important before proving it.

**Comment by rutvikpage** [comment]
Important take-aways from Lecture 7 prep: 

1. Application of reverse triangle inequality while proving that something doesn't converge. 
2. Proof of supremum of a closed set being inside this set. 
3. Proof of all subsequences of a divergent sequence: $(x_n)_{n \in \mathbb{N}} > n$ diverging. -- this is where you choose some $\varepsilon$ such that for all $n > N$, the distance between the supposed limit and the sequence term is unbounded.
