### ISSUE TITLE
TO-DO: 16 Apr 2024

### ISSUE THREAD

**Issue by Page007** [Page007/rutvikpage#2]
To-do things: 

### ANALYSIS

- [x] Lecture 12 
- [x] Lecture 13 prep
- [x] Optional Problems on PSET 2
- [x] Typing out the solutions to PSET 3

### COLLECTIONS

- [x]                    | Level Spec |  Log Spec | 
          |CF|
          |SCF| 
          Coefficients and standard errors like this. 
- [x] ~~Questions on metrics for meeting with Scott.~~

To remember: to find the coefficient for the log specification, collapse the data to a county year level and then conduct the SA analysis.

**Comment by rutvikpage** [comment]
Small Claims Fees: log(number of people sued) :  -.0788 (.058) -- t-stat: -1.36
Civil Filing Fees: log(number of people sued) : -.528 -- t-stat: -1.65
